"""Add currency columns

Revision ID: 19e48d907c89
Revises: 956d3bcee29f
Create Date: 2024-07-20 17:52:59.288626

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19e48d907c89"
down_revision: Union[str, None] = "956d3bcee29f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("currency", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "currency")
    # ### end Alembic commands ###
