"""Add external payment support

Revision ID: 2a06df1125d5
Revises: 19e48d907c89
Create Date: 2024-07-20 18:05:46.726221

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a06df1125d5"
down_revision: Union[str, None] = "19e48d907c89"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("payment_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_id")
    # ### end Alembic commands ###
