"""Add preffered field for wallet

Revision ID: 5abe3dda0a8c
Revises: 2a06df1125d5
Create Date: 2024-07-21 19:07:56.273634

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5abe3dda0a8c"
down_revision: Union[str, None] = "2a06df1125d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("preffered", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "preffered")
    # ### end Alembic commands ###
