"""Initial

Revision ID: 956d3bcee29f
Revises: 
Create Date: 2024-07-20 16:07:00.693955

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "956d3bcee29f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "pending",
                "succeeded",
                "cancelled",
                "waiting_to_capture",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refunds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("idempotency_key", sa.TEXT(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "pending",
                "success",
                "cancelled",
                "waiting_to_capture",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column("money", sa.DECIMAL(), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("payment_method_id", sa.UUID(), nullable=False),
        sa.Column("reccurent_payment", sa.Boolean(), nullable=True),
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wallets")
    op.drop_table("refunds")
    op.drop_table("payments")
    # ### end Alembic commands ###
