"""Fix inconsistenses 

Revision ID: e685e515c0be
Revises: 5abe3dda0a8c
Create Date: 2024-07-28 11:15:38.479119

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e685e515c0be"
down_revision: Union[str, None] = "5abe3dda0a8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refunds", sa.Column("refund_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refunds", "refund_id")
    # ### end Alembic commands ###
