# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from src.core.grpc.models import payment_pb2 as payment__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in payment_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class PaymentManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pay = channel.unary_unary(
            "/PaymentManager/Pay",
            request_serializer=payment__pb2.SubscriptionPaymentRequest.SerializeToString,
            response_deserializer=payment__pb2.SubscriptionPaymentResponse.FromString,
            _registered_method=True,
        )
        self.PayBatch = channel.unary_unary(
            "/PaymentManager/PayBatch",
            request_serializer=payment__pb2.BatchSubscriptionPaymentRequest.SerializeToString,
            response_deserializer=payment__pb2.BatchSubscriptionPaymentResponse.FromString,
            _registered_method=True,
        )


class PaymentManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Pay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PayBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PaymentManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Pay": grpc.unary_unary_rpc_method_handler(
            servicer.Pay,
            request_deserializer=payment__pb2.SubscriptionPaymentRequest.FromString,
            response_serializer=payment__pb2.SubscriptionPaymentResponse.SerializeToString,
        ),
        "PayBatch": grpc.unary_unary_rpc_method_handler(
            servicer.PayBatch,
            request_deserializer=payment__pb2.BatchSubscriptionPaymentRequest.FromString,
            response_serializer=payment__pb2.BatchSubscriptionPaymentResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "PaymentManager", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("PaymentManager", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PaymentManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Pay(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PaymentManager/Pay",
            payment__pb2.SubscriptionPaymentRequest.SerializeToString,
            payment__pb2.SubscriptionPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PayBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PaymentManager/PayBatch",
            payment__pb2.BatchSubscriptionPaymentRequest.SerializeToString,
            payment__pb2.BatchSubscriptionPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
