"""Add created field

Revision ID: 4567aa5f5f14
Revises: e988677c84b3
Create Date: 2024-07-25 21:45:28.247163

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4567aa5f5f14"
down_revision: Union[str, None] = "e988677c84b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_subscriptions",
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_subscriptions", "created")
    # ### end Alembic commands ###
