"""Initial

Revision ID: e988677c84b3
Revises: 
Create Date: 2024-07-22 17:30:19.274330

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e988677c84b3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("tier", sa.INTEGER(), nullable=False),
        sa.Column("code", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column("currency", sa.String(length=255), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column("currency", sa.String(length=255), nullable=False),
        sa.Column("promo_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.BOOLEAN(), nullable=False),
        sa.Column("last_notified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_payed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_subscriptions_user_id"),
        "user_subscriptions",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_subscriptions_user_id"), table_name="user_subscriptions"
    )
    op.drop_table("user_subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
